<script>
    new Promise((resolve,reject) => {
        throw new Error("에러 발생!");
    })
    .finally(() => alert("프라미스가 준비되었습니다"))
    .then(error => alert(error)); // <-- cath에서 에러 객체를 다룰 수 있음
</script>
